stages:

  data_preparation:
    cmd: python data_prep.py -id data/raw -od data/prepared -p params.yaml
    deps:
      - data_prep.py
      - data/raw
    outs:
      - data/prepared
    params:
      - data_preparation

  linear_regression:
    cmd: python linear_regression.py -id data/prepared -od data/models -mn ${linear_regression.model_name}
    deps:
      - linear_regression.py
      - data/prepared
    outs:
      - data/models/${linear_regression.model_name}.csv
      - data/models/${linear_regression.model_name}.joblib
    params:
      - linear_regression

  decision_tree:
    cmd: python decision_tree.py -id data/prepared -od data/models -bm data/models/${linear_regression.model_name}.joblib -mn ${decision_tree.model_name}
    deps:
      - decision_tree.py
      - data/prepared
      - data/models/${linear_regression.model_name}.joblib
    outs:
      - data/models/${decision_tree.model_name}.joblib
    params:
      - decision_tree

  xgboost:
    cmd: python xgboosting.py -id data/prepared -od data/models -bm data/models/${linear_regression.model_name}.joblib -mn ${xgboost.model_name}
    deps:
      - xgboosting.py
      - data/prepared
      - data/models/${linear_regression.model_name}.joblib
    outs:
      - data/models/${xgboost.model_name}.joblib
    params:
      - xgboost

  catboost:
    cmd: python catboosting.py -id data/prepared -od data/models -bm data/models/${linear_regression.model_name}.joblib -mn ${catboost.model_name}
    deps:
      - catboosting.py
      - data/prepared
      - data/models/${linear_regression.model_name}.joblib
    outs:
      - data/models/${catboost.model_name}.joblib
    params:
      - catboost

  neur_network:
    cmd: python neur_network.py -id data/prepared -od data/logs/
    deps:
      - neur_network.py
      - data/prepared
    outs:
      - data/models/neur_network.keras
    params:
      - neur_network