data_preparation:
  train_test_ratio: 0.7
  train_val_ratio: 0.9
  random_state: 42
linear_regression:
  model_name: 'LinearRegression'
decision_tree:
  model_name: 'DecisionTree'
  grid_search:
    max_depth: [ 2, 4, 6, 7 ]
    splitter: [ 'best', 'random' ]
    min_samples_split: [ 2, 3, 4 ]
    min_samples_leaf: [ 1, 2, 3, 4 ]
catboost:
  model_name: 'CatBoost'
  grid_search:
    n_estimators: [ 1, 2, 5, 10, 15 ]
    max_depth: [ 2, 4, 6, 7 ]
    eta: [ 0.3, 0.1, 0.05, 0.01 ]
    subsample: [0.7, 0.8, 0.9, 1]
xgboost:
  model_name: 'XGBoost'
  grid_search:
    n_estimators: [ 1, 2, 5, 10, 15 ]
    max_depth: [ 2, 4, 6, 7 ]
    eta: [ 0.3, 0.1, 0.05, 0.01 ]
    subsample: [0.7, 0.8, 0.9, 1]
neur_network:
  neurons_cnt: [ 64, 128, 256 ]
  batch_size: [ 32, 64, 128 ]
